// <auto-generated />
using System;
using LeaveRequest.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveRequest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715071532_AddAttachments")]
    partial class AddAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LeaveRequest.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("ApprovalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelRequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("ApprovalHistoryId");

                    b.HasIndex("CancelRequestId");

                    b.HasIndex("LeaveRequestId");

                    b.ToTable("ApprovalHistories", (string)null);
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.HasIndex("LeaveRequestId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.CancelRequest", b =>
                {
                    b.Property<Guid>("CancelRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelRequestRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LeaveRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SlaEscalatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SlaReminderSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CancelRequestId");

                    b.HasIndex("CancelRequestRef")
                        .IsUnique();

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("Status", "IsDeleted", "SlaDeadline");

                    b.ToTable("CancelRequests", (string)null);
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AbcStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgencyCompany")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullNameTh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Employees_Email");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Employees_Code");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = "EMP001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Department = "Engineering",
                            Email = "somchai@abc.com",
                            EmployeeCode = "E001",
                            EmployeeType = 1,
                            FullNameEn = "Somchai Jaidee",
                            FullNameTh = "สมชาย ใจดี",
                            HireDate = new DateOnly(2022, 1, 15),
                            IsActive = 1,
                            IsDeleted = 0,
                            ManagerId = "EMP002",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            EmployeeId = "EMP002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Department = "Engineering",
                            Email = "wipa@abc.com",
                            EmployeeCode = "E002",
                            EmployeeType = 1,
                            FullNameEn = "Wipa Rakkan",
                            FullNameTh = "วิภา รักงาน",
                            HireDate = new DateOnly(2019, 6, 1),
                            IsActive = 1,
                            IsDeleted = 0,
                            Position = "Engineering Manager"
                        },
                        new
                        {
                            EmployeeId = "EMP003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Department = "HR",
                            Email = "nanta@abc.com",
                            EmployeeCode = "E003",
                            EmployeeType = 1,
                            FullNameEn = "Nanta Meesuk",
                            FullNameTh = "นันทา มีสุข",
                            HireDate = new DateOnly(2020, 3, 1),
                            IsActive = 1,
                            IsDeleted = 0,
                            ManagerId = "EMP002",
                            Position = "HR Officer"
                        });
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.ImportLog", b =>
                {
                    b.Property<Guid>("ImportLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsRolledBack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SuccessRecords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImportLogId");

                    b.ToTable("ImportLogs", (string)null);
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveBalance", b =>
                {
                    b.Property<string>("LeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarriedForwardDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntitledDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<byte>("LeaveTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeaveYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PendingDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaveBalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "LeaveYear")
                        .IsUnique()
                        .HasDatabaseName("UQ_LeaveBalances_Employee_Type_Year");

                    b.ToTable("LeaveBalances", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveBalanceId = "10000001-0000-0000-0000-000000000001",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP001",
                            EntitledDays = 10m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)1,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 2m
                        },
                        new
                        {
                            LeaveBalanceId = "10000001-0000-0000-0000-000000000002",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP001",
                            EntitledDays = 30m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)2,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 3m
                        },
                        new
                        {
                            LeaveBalanceId = "10000001-0000-0000-0000-000000000003",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP001",
                            EntitledDays = 3m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)3,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 1m
                        },
                        new
                        {
                            LeaveBalanceId = "10000001-0000-0000-0000-000000000004",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP001",
                            EntitledDays = 98m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)4,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            LeaveBalanceId = "10000002-0000-0000-0000-000000000001",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP002",
                            EntitledDays = 10m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)1,
                            LeaveYear = 2026,
                            PendingDays = 3m,
                            UsedDays = 3m
                        },
                        new
                        {
                            LeaveBalanceId = "10000002-0000-0000-0000-000000000002",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP002",
                            EntitledDays = 30m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)2,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 1m
                        },
                        new
                        {
                            LeaveBalanceId = "10000002-0000-0000-0000-000000000003",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP002",
                            EntitledDays = 3m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)3,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            LeaveBalanceId = "10000003-0000-0000-0000-000000000001",
                            CarriedForwardDays = 2m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP003",
                            EntitledDays = 10m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)1,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 5m
                        },
                        new
                        {
                            LeaveBalanceId = "10000003-0000-0000-0000-000000000002",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP003",
                            EntitledDays = 30m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)2,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 0m
                        },
                        new
                        {
                            LeaveBalanceId = "10000003-0000-0000-0000-000000000003",
                            CarriedForwardDays = 0m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EmployeeId = "EMP003",
                            EntitledDays = 3m,
                            IsDeleted = 0,
                            LeaveTypeId = (byte)3,
                            LeaveYear = 2026,
                            PendingDays = 0m,
                            UsedDays = 2m
                        });
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<string>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DurationDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HalfDayPeriod")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("IsHalfDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("LeaveRequestRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<byte>("LeaveTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("LeaveRequestRef")
                        .IsUnique()
                        .HasDatabaseName("UQ_LeaveRequests_Ref");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("IX_LeaveRequests_Employee_Status");

                    b.ToTable("LeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveRequestId = "a0000001-0000-0000-0000-000000000001",
                            ApprovedAt = new DateTime(2026, 2, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            ApprovedBy = "EMP002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "EMP001",
                            DurationDays = 2m,
                            EmployeeId = "EMP001",
                            EndDate = new DateOnly(2026, 2, 4),
                            IsDeleted = 0,
                            IsHalfDay = 0,
                            LeaveRequestRef = "LR-2026-00001",
                            LeaveTypeId = (byte)1,
                            Reason = "ท่องเที่ยวต่างจังหวัด",
                            StartDate = new DateOnly(2026, 2, 3),
                            Status = 2
                        },
                        new
                        {
                            LeaveRequestId = "a0000001-0000-0000-0000-000000000002",
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "EMP001",
                            DurationDays = 1m,
                            EmployeeId = "EMP001",
                            EndDate = new DateOnly(2026, 3, 6),
                            IsDeleted = 0,
                            IsHalfDay = 0,
                            LeaveRequestRef = "LR-2026-00002",
                            LeaveTypeId = (byte)3,
                            Reason = "ธุระส่วนตัว",
                            RejectedAt = new DateTime(2026, 3, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            RejectedBy = "EMP002",
                            RejectionReason = "ช่วงนั้นคนในทีมลาหลายคน กรุณาเลื่อนวันได้ไหม",
                            StartDate = new DateOnly(2026, 3, 6),
                            Status = 3
                        },
                        new
                        {
                            LeaveRequestId = "a0000001-0000-0000-0000-000000000003",
                            CreatedAt = new DateTime(2026, 6, 19, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "EMP001",
                            DurationDays = 2m,
                            EmployeeId = "EMP001",
                            EndDate = new DateOnly(2026, 6, 24),
                            IsDeleted = 0,
                            IsHalfDay = 0,
                            LeaveRequestRef = "LR-2026-00003",
                            LeaveTypeId = (byte)2,
                            Reason = "ไม่สบาย มีไข้",
                            StartDate = new DateOnly(2026, 6, 23),
                            Status = 1
                        },
                        new
                        {
                            LeaveRequestId = "a0000002-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2026, 6, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "EMP002",
                            DurationDays = 3m,
                            EmployeeId = "EMP002",
                            EndDate = new DateOnly(2026, 7, 9),
                            IsDeleted = 0,
                            IsHalfDay = 0,
                            LeaveRequestRef = "LR-2026-00004",
                            LeaveTypeId = (byte)1,
                            Reason = "ไปเที่ยวต่างประเทศ",
                            StartDate = new DateOnly(2026, 7, 7),
                            Status = 1
                        });
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveType", b =>
                {
                    b.Property<byte>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAvailableForOutsource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("MaxDaysPerYear")
                        .HasColumnType("REAL");

                    b.Property<int>("RequiresMedicalCert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeNameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LeaveTypeId");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_LeaveTypes_TypeCode");

                    b.ToTable("LeaveTypes", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveTypeId = (byte)1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsAvailableForOutsource = 0,
                            IsDeleted = 0,
                            MaxDaysPerYear = 10m,
                            RequiresMedicalCert = 0,
                            TypeCode = "ANNUAL",
                            TypeNameEn = "Annual Leave",
                            TypeNameTh = "ลาพักร้อน"
                        },
                        new
                        {
                            LeaveTypeId = (byte)2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsAvailableForOutsource = 1,
                            IsDeleted = 0,
                            MaxDaysPerYear = 30m,
                            RequiresMedicalCert = 1,
                            TypeCode = "SICK",
                            TypeNameEn = "Sick Leave",
                            TypeNameTh = "ลาป่วย"
                        },
                        new
                        {
                            LeaveTypeId = (byte)3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsAvailableForOutsource = 0,
                            IsDeleted = 0,
                            MaxDaysPerYear = 3m,
                            RequiresMedicalCert = 0,
                            TypeCode = "PERSONAL",
                            TypeNameEn = "Personal Leave",
                            TypeNameTh = "ลากิจ"
                        },
                        new
                        {
                            LeaveTypeId = (byte)4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsAvailableForOutsource = 0,
                            IsDeleted = 0,
                            MaxDaysPerYear = 98m,
                            RequiresMedicalCert = 1,
                            TypeCode = "MATERNITY",
                            TypeNameEn = "Maternity Leave",
                            TypeNameTh = "ลาคลอด"
                        });
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("NotificationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudEventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaveRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationLogId");

                    b.HasIndex("CancelRequestId");

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("NotificationLogId", "Status");

                    b.ToTable("NotificationLogs", (string)null);
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.CancelRequest", "CancelRequest")
                        .WithMany()
                        .HasForeignKey("CancelRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeaveRequest.Domain.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany()
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CancelRequest");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany()
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.CancelRequest", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany()
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.Employee", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveBalance", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveRequest.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("LeaveRequest.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveRequest.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.Employee", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("LeaveRequest.Domain.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
